import '../models/recipe_model.dart';

class RecipeService {
  static List<Recipe> getAllRecipes() {
    return [
      Recipe(id: 1, name: 'Menemen', ingredients: ['yumurta', 'domates', 'biber'], category: 'vejetaryen', instructions: 'Sebzeleri doğra, yağda kavur, yumurtayı kır.', duration: 15, servings: 2, difficulty: 'kolay'),
      Recipe(id: 2, name: 'Sucuklu Yumurta', ingredients: ['yumurta', 'sucuk'], category: 'etli', instructions: 'Sucukları tavada kızart, yumurtayı ekle.', duration: 10, servings: 1, difficulty: 'kolay'),
      Recipe(id: 3, name: 'Peynirli Omlet', ingredients: ['yumurta', 'peynir'], category: 'vejetaryen', instructions: 'Yumurtayı çırp, peyniri ekle, tavada pişir.', duration: 12, servings: 1, difficulty: 'kolay'),
      Recipe(id: 4, name: 'Kuru Fasulye', ingredients: ['fasulye', 'soğan', 'salça', 'zeytinyağı'], category: 'vejetaryen', instructions: 'Fasulyeyi haşla, soğan ve salçayla pişir.', duration: 60, servings: 4, difficulty: 'orta'),
      Recipe(id: 5, name: 'Mercimek Çorbası', ingredients: ['mercimek', 'soğan', 'havuç', 'salça'], category: 'vejetaryen', instructions: 'Tüm malzemeleri haşlayıp blenderdan geçir.', duration: 35, servings: 4, difficulty: 'kolay'),
      Recipe(id: 6, name: 'Tavuk Sote', ingredients: ['tavuk', 'soğan', 'biber', 'salça'], category: 'etli', instructions: 'Tavukları ve sebzeleri kavur.', duration: 25, servings: 3, difficulty: 'orta'),
      Recipe(id: 7, name: 'Etli Nohut', ingredients: ['nohut', 'et', 'soğan', 'salça'], category: 'etli', instructions: 'Nohut ve eti haşla, sonra birlikte pişir.', duration: 70, servings: 4, difficulty: 'zor'),
      Recipe(id: 8, name: 'Sebzeli Pilav', ingredients: ['pirinç', 'bezelye', 'havuç'], category: 'vejetaryen', instructions: 'Pirinç ve sebzeleri birlikte kavurup pişir.', duration: 30, servings: 4, difficulty: 'orta'),
      Recipe(id: 9, name: 'Karnıyarık', ingredients: ['patlıcan', 'kıyma', 'soğan', 'biber'], category: 'etli', instructions: 'Patlıcanları kızart, iç harcı doldur ve fırına ver.', duration: 50, servings: 4, difficulty: 'zor'),
      Recipe(id: 10, name: 'Zeytinyağlı Yaprak Sarma', ingredients: ['üzüm yaprağı', 'pirinç', 'soğan', 'zeytinyağı'], category: 'vejetaryen', instructions: 'İç harcı hazırlayıp yapraklara sar, pişir.', duration: 60, servings: 5, difficulty: 'zor'),
      Recipe(id: 11, name: 'İmam Bayıldı', ingredients: ['patlıcan', 'soğan', 'domates', 'zeytinyağı'], category: 'vejetaryen', instructions: 'Patlıcanları doldur, fırına ver.', duration: 45, servings: 3, difficulty: 'orta'),
      Recipe(id: 12, name: 'Menüde Tavuklu Pilav', ingredients: ['tavuk', 'pirinç', 'tereyağı'], category: 'etli', instructions: 'Pilavı pişir, tavukla birlikte servis et.', duration: 35, servings: 4, difficulty: 'orta'),
      Recipe(id: 13, name: 'Fırında Makarna', ingredients: ['makarna', 'peynir', 'yumurta', 'süt'], category: 'vejetaryen', instructions: 'Malzemeleri karıştır, fırında pişir.', duration: 40, servings: 4, difficulty: 'kolay'),
      Recipe(id: 14, name: 'Lazanya', ingredients: ['kıyma', 'domates', 'beşamel sos', 'makarna'], category: 'etli', instructions: 'Kat kat diz, fırında pişir.', duration: 60, servings: 6, difficulty: 'zor'),
      Recipe(id: 15, name: 'Sebzeli Krep', ingredients: ['un', 'süt', 'yumurta', 'kabak'], category: 'vejetaryen', instructions: 'Krep yap, sebzeyle doldur.', duration: 25, servings: 2, difficulty: 'orta'),
      Recipe(id: 16, name: 'Menüde Köfte', ingredients: ['kıyma', 'soğan', 'ekmek', 'baharat'], category: 'etli', instructions: 'Malzemeleri yoğur, kızart veya fırınla.', duration: 30, servings: 4, difficulty: 'orta'),
      Recipe(id: 17, name: 'Patates Kavurma', ingredients: ['patates', 'soğan', 'yağ'], category: 'vejetaryen', instructions: 'Küp doğra, tavada kavur.', duration: 20, servings: 3, difficulty: 'kolay'),
      Recipe(id: 18, name: 'Fırın Tavuk', ingredients: ['tavuk', 'patates', 'havuç'], category: 'etli', instructions: 'Sebzelerle birlikte fırına ver.', duration: 50, servings: 4, difficulty: 'orta'),
      Recipe(id: 19, name: 'Kısır', ingredients: ['bulgur', 'salça', 'domates', 'yeşillik'], category: 'vejetaryen', instructions: 'Bulguru ıslat, malzemelerle karıştır.', duration: 25, servings: 4, difficulty: 'kolay'),
      Recipe(id: 20, name: 'Zeytinyağlı Enginar', ingredients: ['enginar', 'havuç', 'bezelye'], category: 'vejetaryen', instructions: 'Zeytinyağlı olarak pişir.', duration: 40, servings: 3, difficulty: 'orta'),
      Recipe(id: 21, name: 'Mücver', ingredients: ['kabak', 'yumurta', 'un', 'peynir'], category: 'vejetaryen', instructions: 'Kabakları rendele, karışımı kızart.', duration: 30, servings: 3, difficulty: 'orta'),
      Recipe(id: 22, name: 'Zeytinyağlı Taze Fasulye', ingredients: ['taze fasulye', 'soğan', 'domates'], category: 'vejetaryen', instructions: 'Sebzeleri kavur, kısık ateşte pişir.', duration: 40, servings: 4, difficulty: 'orta'),
      Recipe(id: 23, name: 'Çılbır', ingredients: ['yumurta', 'yoğurt', 'tereyağı'], category: 'vejetaryen', instructions: 'Yumurtaları haşla, yoğurtla servis et.', duration: 15, servings: 1, difficulty: 'kolay'),
      Recipe(id: 24, name: 'Tarhana Çorbası', ingredients: ['tarhana', 'su', 'tereyağı'], category: 'vejetaryen', instructions: 'Tarhanayı suda çöz, kaynat.', duration: 25, servings: 3, difficulty: 'kolay'),
      Recipe(id: 25, name: 'Ezogelin Çorbası', ingredients: ['mercimek', 'bulgur', 'salça', 'soğan'], category: 'vejetaryen', instructions: 'Malzemeleri haşla, blenderdan geçir.', duration: 35, servings: 4, difficulty: 'kolay'),
      Recipe(id: 26, name: 'Yoğurtlu Kabak', ingredients: ['kabak', 'yoğurt', 'sarımsak'], category: 'vejetaryen', instructions: 'Kabakları pişir, yoğurtla karıştır.', duration: 25, servings: 2, difficulty: 'kolay'),
      Recipe(id: 27, name: 'Tavuklu Salata', ingredients: ['tavuk', 'marul', 'domates', 'zeytinyağı'], category: 'etli', instructions: 'Tavuğu haşla, doğrayıp karıştır.', duration: 20, servings: 2, difficulty: 'kolay'),
      Recipe(id: 28, name: 'Bulgur Pilavı', ingredients: ['bulgur', 'soğan', 'biber salçası'], category: 'vejetaryen', instructions: 'Soğanı kavur, bulguru ekle ve pişir.', duration: 30, servings: 3, difficulty: 'kolay'),
      Recipe(id: 29, name: 'Fırında Kabak', ingredients: ['kabak', 'peynir', 'yumurta'], category: 'vejetaryen', instructions: 'Kabakları doğra, fırınla.', duration: 35, servings: 3, difficulty: 'orta'),
      Recipe(id: 30, name: 'Fırın Makarna', ingredients: ['makarna', 'süt', 'yumurta', 'kaşar'], category: 'vejetaryen', instructions: 'Tüm malzemeleri karıştır, fırına ver.', duration: 40, servings: 4, difficulty: 'kolay'),
      Recipe(id: 31, name: 'Çorba Sebzeli', ingredients: ['havuç', 'patates', 'soğan'], category: 'vejetaryen', instructions: 'Sebzeleri haşla, blenderdan geçir.', duration: 30, servings: 4, difficulty: 'kolay'),
      Recipe(id: 32, name: 'Patatesli Börek', ingredients: ['yufka', 'patates', 'soğan'], category: 'vejetaryen', instructions: 'İç harcı hazırla, yufkaya sar.', duration: 45, servings: 4, difficulty: 'orta'),
      Recipe(id: 33, name: 'Lahana Sarması', ingredients: ['lahana', 'pirinç', 'soğan'], category: 'vejetaryen', instructions: 'İç harcı hazırla, lahana ile sar.', duration: 60, servings: 5, difficulty: 'zor'),
      Recipe(id: 34, name: 'Kabak Dolması', ingredients: ['kabak', 'pirinç', 'soğan'], category: 'vejetaryen', instructions: 'Kabakları oy, iç harçla doldur.', duration: 50, servings: 4, difficulty: 'orta'),
      Recipe(id: 35, name: 'Kıymalı Makarna', ingredients: ['makarna', 'kıyma', 'salça'], category: 'etli', instructions: 'Makarna haşla, kıymayla karıştır.', duration: 30, servings: 4, difficulty: 'kolay'),
      Recipe(id: 36, name: 'Tavuklu Karnıyarık', ingredients: ['patlıcan', 'tavuk', 'soğan'], category: 'etli', instructions: 'Patlıcanları doldur, fırına ver.', duration: 50, servings: 4, difficulty: 'orta'),
      Recipe(id: 37, name: 'Yoğurtlu Semizotu', ingredients: ['semizotu', 'yoğurt', 'sarımsak'], category: 'vejetaryen', instructions: 'Yıkayıp karıştır, soğuk servis et.', duration: 10, servings: 2, difficulty: 'kolay'),
      Recipe(id: 38, name: 'Domates Çorbası', ingredients: ['domates', 'un', 'tereyağı'], category: 'vejetaryen', instructions: 'Domatesleri ez, unla pişir.', duration: 25, servings: 3, difficulty: 'kolay'),
      Recipe(id: 39, name: 'Etli Kabak', ingredients: ['kabak', 'et', 'soğan'], category: 'etli', instructions: 'Etle birlikte kavur ve pişir.', duration: 35, servings: 3, difficulty: 'orta'),
      Recipe(id: 40, name: 'Yumurtalı Ekmek', ingredients: ['yumurta', 'ekmek', 'süt'], category: 'vejetaryen', instructions: 'Karışımı hazırla, kızart.', duration: 15, servings: 1, difficulty: 'kolay'),
      Recipe(id: 41, name: 'Mantı', ingredients: ['un', 'kıyma', 'yoğurt'], category: 'etli', instructions: 'Hamuru aç, kıyma koy, haşla, yoğurtla servis et.', duration: 60, servings: 5, difficulty: 'zor'),
      Recipe(id: 42, name: 'Çoban Salata', ingredients: ['domates', 'salatalık', 'soğan'], category: 'vejetaryen', instructions: 'Tüm malzemeleri doğrayıp karıştır.', duration: 10, servings: 2, difficulty: 'kolay'),
      Recipe(id: 43, name: 'Taze Fasulye Yemeği', ingredients: ['fasulye', 'soğan', 'domates'], category: 'vejetaryen', instructions: 'Klasik zeytinyağlı usulde pişir.', duration: 40, servings: 3, difficulty: 'orta'),
      Recipe(id: 44, name: 'Sebzeli Omlet', ingredients: ['yumurta', 'kabak', 'biber'], category: 'vejetaryen', instructions: 'Sebzeleri kavur, yumurtayı ekle.', duration: 20, servings: 2, difficulty: 'kolay'),
      Recipe(id: 45, name: 'Fırında Mücver', ingredients: ['kabak', 'yumurta', 'un'], category: 'vejetaryen', instructions: 'Mücver harcını fırında pişir.', duration: 30, servings: 4, difficulty: 'orta'),
      Recipe(id: 46, name: 'Arpa Şehriye Çorbası', ingredients: ['şehriye', 'salça', 'yağ'], category: 'vejetaryen', instructions: 'Şehriyeyi kavur, salçayla pişir.', duration: 20, servings: 3, difficulty: 'kolay'),
      Recipe(id: 47, name: 'Brokoli Graten', ingredients: ['brokoli', 'süt', 'kaşar'], category: 'vejetaryen', instructions: 'Brokoliyi haşla, sosla fırına ver.', duration: 35, servings: 4, difficulty: 'orta'),
      Recipe(id: 48, name: 'Kabak Mücver', ingredients: ['kabak', 'yumurta', 'peynir'], category: 'vejetaryen', instructions: 'Karışımı tavada kızart.', duration: 25, servings: 3, difficulty: 'kolay'),
      Recipe(id: 49, name: 'Yoğurt Çorbası', ingredients: ['yoğurt', 'pirinç', 'nane'], category: 'vejetaryen', instructions: 'Yoğurdu kesmeden pişir.', duration: 25, servings: 4, difficulty: 'orta'),
      Recipe(id: 50, name: 'Sulu Köfte', ingredients: ['kıyma', 'pirinç', 'patates', 'soğan'], category: 'etli', instructions: 'Köfteleri yuvarla, sebzelerle pişir.', duration: 45, servings: 4, difficulty: 'orta'),
    ];
  }
}